### ISSUE TITLE
`osu.Game.Resources.csproj` not found

### ISSUE THREAD

**Issue by catzy007** [Alexmitter/osu-lazer-linux-installer#12] opened 2019-05-10 20:44 UTC
hello, i'm currently trying to build and run osu-stable 2018.1228 and this happen

osu!lazer installer for linux
This script will clone osu!lazer and build it.
Cloning into 'osu-stable'...
remote: Enumerating objects: 138924, done.
remote: Total 138924 (delta 0), reused 0 (delta 0), pack-reused 138924
Receiving objects: 100% (138924/138924), 71.35 MiB | 680.00 KiB/s, done.
Resolving deltas: 100% (108538/108538), done.
/usr/share/dotnet/sdk/2.2.203/NuGet.targets(246,5): error MSB3202: The project file "/home/catzy/UMBRELLA/builderx/osu-lazer-linux-installer/scripts/osu-stable/osu-resources/osu.Game.Resources/osu.Game.Resources.csproj" was not found. [/home/catzy/UMBRELLA/builderx/osu-lazer-linux-installer/scripts/osu-stable/osu.sln]
Microsoft (R) Build Engine version 16.0.450+ga8dc7f1d34 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

/usr/share/dotnet/sdk/2.2.203/NuGet.targets(246,5): error MSB3202: The project file "/home/catzy/UMBRELLA/builderx/osu-lazer-linux-installer/scripts/osu-stable/osu-resources/osu.Game.Resources/osu.Game.Resources.csproj" was not found. [/home/catzy/UMBRELLA/builderx/osu-lazer-linux-installer/scripts/osu-stable/osu.sln]

Build FAILED.

/usr/share/dotnet/sdk/2.2.203/NuGet.targets(246,5): error MSB3202: The project file "/home/catzy/UMBRELLA/builderx/osu-lazer-linux-installer/scripts/osu-stable/osu-resources/osu.Game.Resources/osu.Game.Resources.csproj" was not found. [/home/catzy/UMBRELLA/builderx/osu-lazer-linux-installer/scripts/osu-stable/osu.sln]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.43

**Comment by Li4n0** [comment] 2019-06-22 04:12
I have the save problem.

**Comment by Alexmitter** [comment] 2019-08-22 18:13
@catzy007 @Li4n0 I am so sorry that it took so long. The issue is that osu!lazer had changes to its folder structure that are not reflected by what I wrote back then for the stable function. I will update the stable releases and add a warning that those can break.
I hope you noticed that the Daily function works fine.
If you have any further issues with that, please feel free to add them here.

**Comment by Alexmitter** [comment] 2019-08-22 18:18
Fixed with commit 9f62352a3a7e0a49363f0cff9aa308e9192fc1ab

**Closed as completed by Alexmitter** 2019-08-22 18:18 UTC
